/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp9_Ej2;

/**
 *
 * @author messi
 */
public class JFrame_MostrarArtistas extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_MostrarArtistas
     */
    public JFrame_MostrarArtistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelCrearArtista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        crearArtistaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArtistasContainer = new javax.swing.JList<>();
        InfoArtistaBtn = new javax.swing.JButton();
        PanelDataArtista = new javax.swing.JPanel();
        eliminarArtistaBtn = new javax.swing.JButton();
        editarArtista = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        InstrumentoArtista = new javax.swing.JLabel();
        TipoMusicaArtista = new javax.swing.JLabel();
        BandaArtista = new javax.swing.JLabel();
        NombreArtista = new javax.swing.JLabel();
        FechaDeNacimientoArtista = new javax.swing.JLabel();
        ReproducirSon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCrearArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelCrearArtista.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Artistas Creados");

        crearArtistaBtn.setText("Crear Cantor");
        crearArtistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearArtistaBtnActionPerformed(evt);
            }
        });

        ArtistasContainer.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ArtistasContainer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ArtistasContainer);

        InfoArtistaBtn.setText("Ver Info Del Artista");
        InfoArtistaBtn.setActionCommand("Ver Info Del Cantor");
        InfoArtistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoArtistaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCrearArtistaLayout = new javax.swing.GroupLayout(PanelCrearArtista);
        PanelCrearArtista.setLayout(PanelCrearArtistaLayout);
        PanelCrearArtistaLayout.setHorizontalGroup(
            PanelCrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearArtistaLayout.createSequentialGroup()
                .addGroup(PanelCrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCrearArtistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InfoArtistaBtn)
                        .addGap(25, 25, 25)
                        .addComponent(crearArtistaBtn))
                    .addGroup(PanelCrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCrearArtistaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelCrearArtistaLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCrearArtistaLayout.setVerticalGroup(
            PanelCrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearArtistaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PanelCrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearArtistaBtn)
                    .addComponent(InfoArtistaBtn))
                .addContainerGap())
        );

        PanelDataArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        eliminarArtistaBtn.setText("Eliminar Artista");
        eliminarArtistaBtn.setToolTipText("");
        eliminarArtistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarArtistaBtnActionPerformed(evt);
            }
        });

        editarArtista.setText("Editar Artista");
        editarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarArtistaActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Title.setText("Info Artista");

        InstrumentoArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InstrumentoArtista.setText("Instrumento");

        TipoMusicaArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TipoMusicaArtista.setText("Tipo De Musica");

        BandaArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BandaArtista.setText("Banda");

        NombreArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NombreArtista.setText("Nombre Artista");

        FechaDeNacimientoArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FechaDeNacimientoArtista.setText("Fecha De Nacimiento");

        ReproducirSon.setText("Reproducir");

        javax.swing.GroupLayout PanelDataArtistaLayout = new javax.swing.GroupLayout(PanelDataArtista);
        PanelDataArtista.setLayout(PanelDataArtistaLayout);
        PanelDataArtistaLayout.setHorizontalGroup(
            PanelDataArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                        .addComponent(editarArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarArtistaBtn))
                    .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                        .addComponent(InstrumentoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReproducirSon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                        .addComponent(TipoMusicaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addComponent(BandaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FechaDeNacimientoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        PanelDataArtistaLayout.setVerticalGroup(
            PanelDataArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstrumentoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(ReproducirSon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoMusicaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BandaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaDeNacimientoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addGroup(PanelDataArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarArtistaBtn)
                    .addComponent(editarArtista))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDataArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(PanelCrearArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCrearArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDataArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearArtistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearArtistaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearArtistaBtnActionPerformed

    private void InfoArtistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoArtistaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoArtistaBtnActionPerformed

    private void editarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarArtistaActionPerformed

    private void eliminarArtistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarArtistaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarArtistaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArtistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArtistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArtistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MostrarArtistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_MostrarArtistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> ArtistasContainer;
    public javax.swing.JLabel BandaArtista;
    public javax.swing.JLabel FechaDeNacimientoArtista;
    public javax.swing.JButton InfoArtistaBtn;
    public javax.swing.JLabel InstrumentoArtista;
    public javax.swing.JLabel NombreArtista;
    public javax.swing.JPanel PanelCrearArtista;
    public javax.swing.JPanel PanelDataArtista;
    public javax.swing.JButton ReproducirSon;
    public javax.swing.JLabel TipoMusicaArtista;
    private javax.swing.JLabel Title;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton crearArtistaBtn;
    public javax.swing.JButton editarArtista;
    public javax.swing.JButton eliminarArtistaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
